server:
  port: 9090

#数据库连接配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/alone?serverTimezone=GMT%2b8
    username: root
    password: root
#mybatis配置
mybatis:
#  classpath 表示resources文件夹
  mapper-locations: classpath:mapper/*.xml #扫描所有mybatis的xml文件
